=== MauroPB30/M0373_XML_DTD/Equipos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="equipos">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="equipo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="nombreEquipo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="3" />
                                        <xs:maxLength value="20" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="tipoTrabajo" type="xs:string" />
                            <xs:element name="directorEquipo" type="xs:string" />

                            <xs:element name="resultados">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="año" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="exitos">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                                <xs:minInclusive value="0" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="fracasos">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                                <xs:minInclusive value="0" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="valor" type="xs:integer"
                                                    use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="integrantes">
                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="integrante" minOccurs="1"
                                            maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>

                                                    <xs:element name="nombre">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:minLength value="3" />
                                                                <xs:maxLength value="20" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>

                                                    <xs:element name="apellido">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:minLength value="3" />
                                                                <xs:maxLength value="20" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>

                                                    <xs:element name="cargo">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:minLength value="3" />
                                                                <xs:maxLength value="20" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>

                                                    <xs:element name="fechaNacimiento">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:date">
                                                                <xs:maxExclusive value="2000-01-01" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>

                                                    <xs:element name="imagen" type="xs:string" />
                                                    <xs:element name="ultimaHoraInicio"
                                                        type="xs:time" />
                                                    <xs:element name="ultimaFechaInicio"
                                                        type="xs:date" />

                                                    <xs:element name="estadisticas">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element
                                                                    name="programasRealizados"
                                                                    type="xs:integer" />
                                                                <xs:element name="erroresCorregidos"
                                                                    type="xs:integer" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>

                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== MauroPB30/M0373_XML_DTD/Equipos.xml
<?xml version="1.0" encoding="UTF-8"?>
<equipos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Equipos.xsd">

    <equipo>
        <nombreEquipo>DevMasters</nombreEquipo>
        <tipoTrabajo>desarrollo de software</tipoTrabajo>
        <directorEquipo>Carlos Perez</directorEquipo>

        <resultados>
            <año valor="2023">
                <exitos>5</exitos>
                <fracasos>2</fracasos>
            </año>
            <año valor="2024">
                <exitos>7</exitos>
                <fracasos>1</fracasos>
            </año>
        </resultados>

        <integrantes>
            <integrante>
                <nombre>Ana</nombre>
                <apellido>Lopez</apellido>
                <cargo>Programador</cargo>
                <fechaNacimiento>1995-06-12</fechaNacimiento>
                <imagen>imagenes/ana.png</imagen>
                <ultimaHoraInicio>08:30:00</ultimaHoraInicio>
                <ultimaFechaInicio>2024-11-10</ultimaFechaInicio>

                <estadisticas>
                    <programasRealizados>12</programasRealizados>
                    <erroresCorregidos>30</erroresCorregidos>
                </estadisticas>
            </integrante>

            <integrante>
                <nombre>Mario</nombre>
                <apellido>Gomez</apellido>
                <cargo>Analista</cargo>
                <fechaNacimiento>1990-03-22</fechaNacimiento>
                <imagen>imagenes/mario.png</imagen>
                <ultimaHoraInicio>09:00:00</ultimaHoraInicio>
                <ultimaFechaInicio>2024-11-12</ultimaFechaInicio>

                <estadisticas>
                    <programasRealizados>8</programasRealizados>
                    <erroresCorregidos>18</erroresCorregidos>
                </estadisticas>
            </integrante>
        </integrantes>

    </equipo>

</equipos>
