=== MauroPB30/M0373_XML_DTD/libro.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo"></xs:element>
                <xs:element name="escritores">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="escritor"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="publicacion"></xs:element>
                <xs:element name="generos">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="genero"></xs:element>
                            <xs:element name="genero"></xs:element>
                            <xs:element name="genero"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MauroPB30/M0373_XML_DTD/libro.xml
<?xml version="1.0" encoding="UTF-8"?>
<libro  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="libro.xsd">
    <titulo ediciones="15">El se√±or de los anillos</titulo>
    <escritores>
        <escritor>J.RR.Tolkien</escritor>
    </escritores>
    <publicacion>2015-05-08</publicacion>
    <generos>
        <genero>fantaastico</genero>
        <genero>aventuras</genero>
        <genero>romance</genero>
    </generos>
</libro>
