=== MauroPB30/M0373_XML_DTD/musica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="musica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="grupo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre"></xs:element>
                            <xs:element name="genero"></xs:element>
                            <xs:element name="contacto">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="email"></xs:element>
                                        <xs:element name="facebook"></xs:element>
                                        <xs:element name="instagram"></xs:element>
                                        <xs:element name="x"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="web"></xs:element>
                            <xs:element name="integrantes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="integrante" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre"></xs:element>
                                                    <xs:element name="edad"></xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="funcion" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="vocalista"></xs:enumeration>
                                                            <xs:enumeration value="bajo"></xs:enumeration>
                                                            <xs:enumeration value="bateria"></xs:enumeration>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MauroPB30/M0373_XML_DTD/Musica.xml
<?xml version="1.0" encoding="UTF-8"?>
<musica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="musica.xsd">

    <grupo name="1">
        <nombre>Green Day</nombre>
        <genero>pop</genero>
        <contacto>
            <email>press@crushmusic.com</email>
            <facebook>https://www.facebook.com/GreenDay/</facebook>
            <instagram>https://www.instagram.com/greenday</instagram>
            <x>https://x.com/greenday</x>
        </contacto>
        <web>https://www.greendayofficial.com</web>
        <integrantes>
            <integrante funcion="vocalista">
                <nombre>Billie Joe Armstrong</nombre>
                <edad>52</edad>
            </integrante>
            <integrante funcion="bajo">
                <nombre>Mike Dirnt</nombre>
                <edad>51</edad>
            </integrante>
            <integrante funcion="bateria">
                <nombre>Tre Cool</nombre>
                <edad>50</edad>
            </integrante>
        </integrantes>
    </grupo>

    <grupo name="2">
        <nombre>Soda Estereo</nombre>
        <genero>pop</genero>
        <contacto>
            <email>tour@sodastereo.com</email>
            <facebook>https://www.facebook.com/sodastereo/?locale=es_ES</facebook>
            <instagram>https://www.instagram.com/sodastereo</instagram>
            <x>https://x.com/sodastereo</x>
        </contacto>
        <web>https://www.sodastereooficial.com</web>
        <integrantes>
            <integrante funcion="vocalista">
                <nombre>Gustavo Cerati</nombre>
                <edad>55</edad>
            </integrante>
            <integrante funcion="bajo">
                <nombre>Zeta Bosio</nombre>
                <edad>68</edad>
            </integrante>
            <integrante funcion="bateria">
                <nombre>Charly Alberti</nombre>
                <edad>62</edad>
            </integrante>
        </integrantes>
    </grupo>

</musica>
